#! /bin/sh
#
# Generate the tab-separated evaluation results for unipartite datasets
# (part 2).     
#

set -e

TMP_FILE=${TMP:-/tmp}/`basename $0`.$$

CORPORA="`cat dataset-list-eval`"
export CORPORA="`echo $CORPORA`"

export OUTPUT=$TMP_FILE.out

export FILTER_RELATIONSHIP_FORMAT="6"

export METHODS_ASYM="poly polyn sinh neuodd dim_lin sne_squ" 
export METHODS_BACK="poly polyn sinh neuodd dim_lin sne_squ" 

export SHORT_NAME=1
export HIDE_SIZE=1

cd ../webstore/analysis/

../matlab/matlab result2 

cat $TMP_FILE.out
