#! /bin/sh
#
# Generate the signed bipartite evaluation results. 
#
# PARAMETERS
#	$1 bar chart name
#

set -e

TMP_FILE=${TMP:-/tmp}/`basename $0`.$$

CORPORA="movielens-100k_rating movielens-1m movielens-10m_rating netflix bx epinions-rating filmtipset_rating jester"
export CORPORA

export OUTPUT=$TMP_FILE.out
export OUTPUT_BAR="`pwd`/$1"

export METHODS_PATHA="pref" 
export METHODS_BIP="polyn sinh neuodd" 
export METHODS_BIPN="lapodd ratodd" 
export METHODS_LAPB="lrat"
export METHODS_EXTRBIP="sne_abs"

export HIDE_SIZE=1
export HIDE_TYPE_NAME=1

cd ../webstore/analysis/

../matlab/matlab result2 

cat $TMP_FILE.out
