
proposal.pdf:  proposal.tex  kunegis.bib
	pdflatex proposal.tex
	bibtex proposal
	pdflatex proposal.tex
	pdflatex proposal.tex


kunegis.bib:  ../../bibtex/kunegis.bib
	cp ../../bibtex/kunegis.bib .

