#! /bin/bash
#
# A simple variant of ./headers for shorter tables.
#
# PARAMETERS
#	$HEADER	The header line, with fields separated by
#		"&"; when not given, the header must be given in the
#		first line of input

set -e 

sort |
while read -r line
do
    echo "$line" | sed -re 's,^[^ ]+ ,,'
done
